version: '3.2'

services:
  builder:
    build: resources
    volumes:
      - type: volume
        source: webdata
        target: /home/ubuntu/webdata

  prod:
   image: tomcat
   depends_on:
     - builder
   volumes:
     - type: volume
       source: webdata
       target: /usr/local/tomcat/webapps

   ports:
     - '8080:8080'

volumes:
  webdata:



